name: syswo_http
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  chopper: ^8.5.0
  syswo_core:
    git:
      url: https://github.com/wandx/syswo.git
      ref: develop
      path: packages/syswo_core
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
